linkedList={
    "value":12,
    "next":{
        "value":134,
        "next":{
            "value":56,
            "next":{
                "value":45,
                "next":{
                    "value":34,
                    "next":None,
                }
            }
        }
    }
}
print(linkedList["next"]["next"]["next"]["value"])